/**
 * Render the generated media client. It is a thin binding over the single runtime
 * client (`@dudousxd/nestjs-media-client`) — the wire protocol lives there, not here,
 * so there is exactly one implementation to maintain. The generated file only bakes
 * in the configured tus base path.
 */
export function renderMediaClient(basePath: string): string {
  return `// Generated by @dudousxd/nestjs-media-codegen — do not edit.
// Thin binding over @dudousxd/nestjs-media-client with the project's tus base path.
import {
  mediaUrl,
  uploadMedia as uploadMediaBase,
  type UploadMediaOptions,
  type UploadMediaResult,
} from '@dudousxd/nestjs-media-client';

const BASE_PATH = ${JSON.stringify(basePath)};

/** Resumable (tus) upload to this project's media endpoint. */
export function uploadMedia(
  data: Blob,
  options: Omit<UploadMediaOptions, 'basePath'>,
): Promise<UploadMediaResult> {
  return uploadMediaBase(data, { basePath: BASE_PATH, ...options });
}

export { mediaUrl };
export type { UploadMediaOptions, UploadMediaResult };
`;
}
